
import { DM_Sans } from 'next/font/google';
import "./globals.css";



const dmSans = DM_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '700'],  // Choose the weights you need
  display: 'swap',               // Optional: improve CLS
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.className} antialiased bg-white`}
      >
        {children}
      </body>
    </html>
  );
}
